[[files]]
file = "/efi/EFI/refind/refind.conf"
tags = [
	"refind"
]

[[files]]
file = "/efi/EFI/refind/refind-theme-regular/"
tags = [
	"refind"
]

[[files]]
file = "/root/.nanorc"
tags = [
	"nano"
]
