#
# setups
#


#
# ignores
#

[[ignores]]
file = "/bash-it/"

[[ignores]]
file = "/oh-my-zsh/"

#
# ~
#

[[files]]
file = "/.bash_logout"
tags = [
	"bash"
]

[[files]]
file = "/.bash_profile"
tags = [
	"bash"
]

[[files]]
file = "/.bashrc"
tags = [
	"bash"
]

[[files]]
file = "/.cliflix.json"
tags = [
	"cliflix"
]

[[files]]
file = "/.fehbg"
tags = [
	"feh"
]


[[files]]
file = "/.profile"
tags = [
	"shell"
]

[[files]]
file = "/zprofile"
tags = [
	"zsh"
]

[[files]]
file = "/zshrc"
tags = [
	"zsh"
]

[[files]]
file = "/.yarnrc"
tags = [
	"yarn"
]

#
# ~/bin
#

[[files]]
file = "/bin/"

#
# ~/config
#

[[files]]
file = "/user-dirs.dirs"

[[files]]
file = "/alacritty/"
tags = [
	"alacritty"
]

[[files]]
file = "/awesome/"
tags = [
	"awesome"
]

[[files]]
file = "/bash/"
tags = [
	"bash"
]

[[files]]
file = "/bat/"
tags = [
	"bat"
]

[[files]]
file = "/broot/"
tags = [
	"broot"
]

[[files]]
file = "/calcurse/"
tags = [
	"calcurse"
]

[[files]]
file = "/cava/"
tags = [
	"cava"
]

[[files]]
file = "/chezmoi/"
tags = [
	"chezmoi"
]

[[files]]
file = "/cmus/rc"
tags = [
	"cmus"
]

[[files]]
file = "/Code/User/keybindings.json"
tags = [
	"vscode"
]

[[files]]
file = "/Code/User/settings.json"
tags = [
	"vscode"
]

[[files]]
file = "/curl/"
tags =  [
	"curl"
]

[[files]]
file = "/dircolors/"

[[files]]
file = "/fish/"
tags = [
	"fish"
]

[[files]]
file = "/dunst/"
tags = [
	"dunst"
]

[[files]]
file = "/fish/"
tags = [
	"fish"
]

[[files]]
file = "/fontconfig/"

[[files]]
file = "/gh/"
tags = [
	"gh"
]

[[files]]
file = "/git/"
tags = [
	"git"
]

[[files]]
file = "/hg/"
tags = [
	"mercurial"
]

[[files]]
file = "/htop/"
tags = [
	"htop"
]

[[files]]
file = "/i3/"
tags = [
	"i3"
]

[[files]]
file = "/i3status/"
tags = [
	"i3status"
]

[[files]]
file = "/info/"
tags = [
	"info"
]

[[files]]
file = "/ion/"
tags = [
	"ion"
]

[[files]]
file = "/kitty/"
tags = [
	"kitty"
]

[[files]]
file = "/lazydocker/"
tags = [
	"docker"
]

[[files]]
file = "/maven/"

[[files]]
file = "/micro/"
tags = [
	"micro"
]

[[files]]
file = "/mnemosyne/config.py"
tags = [
	"mnemosyne"
]

[[files]]
file = "/nano/"
tags = [
	"nano"
]

[[files]]
file = "/neofetch/"
tags = [
	"neofetch"
]

[[files]]
file = "/nimble/"
tags = [
	"nimble"
]

[[files]]
file = "/nitrogen/"
tags = [
	"nitrogen"
]

[[files]]
file = "/npm/"
tags = [
	"npm"
]

[[files]]
file = "/nu/"
tags = [
	"nu"
]

[[files]]
file = "/nvim/"
tags = [
	"nvim"
]

[[files]]
file = "/picom/"
tags = [
	"picom"
]

[[files]]
file = "/polybar/"
tags = [
	"polybar"
]

[[files]]
file = "/pulse/"
tags = [
	"pulse"
]

[[files]]
file = "/python/"
tags = [
	"python"
]

[[files]]
file = "/ranger/"
tags = [
	"ranger"
]

[[files]]
file = "/readline/"
tags = [
	"bash", "redline"
]

[[files]]
file = "/redshift/"
tags = [
	"redshift"
]

[[files]]
file = "/ripgrep/"
tags = [
	"ripgrep"
]

[[files]]
file = "/rofi/"
tags = [
	"rofi"
]

[[files]]
file = "/rtorrent"
tags = [ "rtorrent" ]

[[files]]
file = "/salamis/"
tags = [ "salamis" ]

[[files]]
file = "/starship/"
tags = [ "starship" ]

[[files]]
file = "/systemd"
tags = [ "systemd" ]

[[files]]
file = "/terminator/"
tags = [ "terminator" ]

[[files]]
file = "/termite/"
tags = [
	"termite"
]

[[files]]
file = "/tilda/"
tags = [
	"tilda"
]

[[files]]
file = "/tmux/"
tags = [
	"tmux"
]

[[files]]
file = "/vim/"
tags = [
	"vim"
]

[[files]]
file = "/wget/"
tags = [
	"wget"
]

[[files]]
file = "/X11/"
tags = [
	"X"
]

[[files]]
file = "/xob/"
tags = [
	"xob"
]

[[files]]
file = "/yay/"
tags = [
	"yay"
]

[[files]]
file = "/zsh/"
tags = [
	"zsh"
]

[[files]]
file = "/pamix.conf"
tags = [
	"pamix"
]

[[files]]
file = "/pulsemixer.cfg"
tags = [
	"pulsemixer"
]

#
# ~/data
#

[[files]]
file = "/calcurse.desktop"
tags = [
	"calcurse"
]

[[files]]
file = "/Nemo.desktop"
tags = [
	"nemo"
]

[[files]]
file = "/Obsidian.desktop"
tags = [
	"obsidian"
]

[[files]]
file = "/Zettlr.desktop"
tags = [
	"zettlr"
]

#
# ~/scripts
#

[[files]]
file = "/scripts/"
