root = "./user"


[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/colors/"
files = ["nord"]
post = ".vim"
dest = "config/vim/themes"
destPost = ".theme.vim"
tags = "vim"

[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-tmux/develop/src/"
files = ["nord", "nord-status-content", "nord-status-content-no-patched-font"]
post = ".conf"
dest = "config/dircolors/themes"
destPost = ".conf"
tags = ["tmux"]

[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-alacritty/develop/src/"
post = ".yml"
files = ["nord"]
dest = "config/alacritty/themes"
destPost = ".theme.yaml"
tags = "alacritty"

[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-xresources/develop/src/"
post = ""
files = ["nord"]
dest = "config/X11/themes"
destPost = ".theme.xresources"
tags = "xresources"


[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/"
files = ["dir_colors"]
post = ""
dest = "config/dircolors/themes"
destPost = ".theme"
tags = "dircolors"


[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-termite/develop/src/"
files = ["config"]
post = ""
dest = "config/termite/themes"
destPost = ".theme.conf"
tags = ["termite"]


[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-terminator/develop/src/"
files = ["config"]
post = ""
dest = "config/terminator/themes"
destPost = ".theme.conf"
tags = ["terminator"]

[[urls]]
pre = "https://raw.githubusercontent.com/arcticicestudio/nord-terminator/develop/src/"
files = ["config"]
post = ""
dest = "config/terminator/themes"
destPost = ".theme.conf"
tags = ["terminator"]
