[[files]]
file = ".bash_logout"
tags = [
	"bash"
]

[[files]]
file = "xfce4/terminal"
type = "folder"
tags = [
	"xfce4"
]

# [[files]]
# file = ".bash_profile"
# tags = [
# 	"bash"
# ]

# [[files]]
# file = ".bashrc"
# tags = [
# 	"bash"
# ]

# [[files]]
# file = ".cliflix.json"
# tags = [
# 	"cliflix"
# ]

# [[files]]
# file = ".cshrc"
# tags = [
# 	"cshrc"
# ]

# [[files]]
# file = ".fehbg"
# tags = [
# 	"feh"
# ]

# [[files]]
# file = ".kshrc"
# tags = [
# 	"ksh"
# ]

# [[files]]
# file = ".login"
# tags = [
# 	"cshrc", "tcshrc"
# ]

# [[files]]
# file = ".profile"
# tags = [
# 	"shell"
# ]

# [[files]]
# file = ".rcrc"
# tags = [
# 	"rcm"
# ]

# [[files]]
# file = ".tcshrc"
# tags = [
# 	"tcshrc"
# ]

# [[files]]
# file = ".xinitrc"
# tags = [
# 	"X"
# ]

# [[files]]
# file = ".xprofile"
# tags = [
# 	"X"
# ]

# [[files]]
# file = ".Xresources"
# tags = [
# 	"X"
# ]

# [[files]]
# file = ".zprofile"
# tags = [
# 	"zsh"
# ]

# [[files]]
# file = ".zshrc"
# tags = [
# 	"zsh"
# ]
