files:
   - path: .editorconfig
     op: add
     for: [all]
     tags: [core]
     usage: single

   - path: .gitattributes
     op: add
     for: [all]
     tags: [core]

   - path: .prettierrc.json
     op: add
     for: ['javascript']
     tags: [javascript, typescript]

   - path: CODE_OF_CONDUCT.md
     op: add
     for: [all]
     tags: [contrib]

   - path: CONTRIBUTING.md
     op: add
     for: [all]
     tags: [contrib]

   - path: jsconfig.json
     op: add
     for: [js]
     endings: ['js', 'jsx']

   - path: LICENSE
     op: add
     for: [all]
     tags: [contrib]

   - path: .github/CODE_OF_CONDUCT.md
     op: remove
     for: [all]
     tags: [contrib]

   - path: .github/COMMIT_CONVENTION.md
     op: add
     for: [all]
   - path: .github/CONTRIBUTING.md
     op: remove
     for: [all]
     tags: [contrib]

   - path: .github/PULL_REQUEST_TEMPLATE.md
     op: add
     for: [all]
     tags: [contrib]

   - path: .github/ISSUE_TEMPLATE/BUG_REPORT.md
     op: add
     for: [all]
     tags: [contrib]

   - path: .github/ISSUE_TEMPLATE/config.yml
     op: add
     for: [all]
     tags: [contrib]

   - path: .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
     op: add
     for: [all]
     tags: [contrib]

   - path: .github/ISSUE_TEMPLATE/QUESTION.md
     op: add
     for: [all]
     tags: [contrib]

   - path: .globe/globe.state
     op: remove
     for: [all]
     tags: [core]

   - path: scripts/globe/go.sh
     op: add
     for: [golang]
     endings: ['go']
