#
# ~
#

[[files]]
file = "/.bash_logout"
tags = [
	"bash"
]

[[files]]
file = "/.bash_profile"
tags = [
	"bash"
]

[[files]]
file = "/.bashrc"
tags = [
	"bash"
]

[[files]]
file = "/.cliflix.json"
tags = [
	"cliflix"
]

[[files]]
file = "/.cshrc"
tags = [
	"cshrc"
]

[[files]]
file = "/.fehbg"
tags = [
	"feh"
]

[[files]]
file = "/.kshrc"
tags = [
	"ksh"
]

[[files]]
file = "/.login"
tags = [
	"cshrc", "tcshrc"
]

[[files]]
file = "/.profile"
tags = [
	"shell"
]

[[files]]
file = "/.rcrc"
tags = [
	"rcm"
]

[[files]]
file = "/.tcshrc"
tags = [
	"tcshrc"
]

[[files]]
file = "/.xinitrc"
tags = [
	"X"
]

[[files]]
file = "/.xprofile"
tags = [
	"X"
]

[[files]]
file = "/.Xresources"
tags = [
	"X"
]

[[files]]
file = "/.zprofile"
tags = [
	"zsh"
]

[[files]]
file = "/.zshrc"
tags = [
	"zsh"
]

#
# ~/.config
#

[[files]]
file = "/user-dirs.dirs"

[[files]]
file = "/alacritty/"

[[files]]
file = "/awesome/"

[[files]]
file = "/bash/"

[[files]]
file = "/calcurse/"

[[files]]
file = "/cava/"

[[files]]
file = "/chezmoi/"

[[files]]
file = "/cmus/rc"

[[files]]
file = "/Code/User/keybindings.json"

[[files]]
file = "/Code/User/settings.json"

[[files]]
file = "/curl/"

[[files]]
file = "/dircolors/"

[[files]]
file = "/fish/"

[[files]]
file = "/fontconfig/"

[[files]]
file = "/gh/"

[[files]]
file = "/git/"

[[files]]
file = "/gnupg/gpg-agent.conf"

[[files]]
file = "/hg/"

[[files]]
file = "/i3/"
tags = [
	"i3"
]

[[files]]
file = "/i3status/"
tags = [
	"i3status"
]

[[files]]
file = "/info/"

[[files]]
file = "/ion/"
tags = [
	"ion"
]

[[files]]
file = "/kitty/"

[[files]]
file = "/maven/"

[[files]]
file = "/micro/bindings.json"
tags = [
	"micro"
]

[[files]]
file = "/micro/settings.json"
tags = [
	"micro"
]

[[files]]
file = "/mnemosyne/config.py"
tags = [
	"mnemosyne"
]

[[files]]
file = "/nano/"

[[files]]
file = "/neofetch/"

[[files]]
file = "/npm/"

[[files]]
file = "/nu/"

[[files]]
file = "/nvim/"

[[files]]
file = "/picom/"

[[files]]
file = "/polybar/"

[[files]]
file = "/ranger/"
tags = [
	"ranger"
]

[[files]]
file = "/readline/"
tags = [
	"bash", "redline"
]

[[files]]
file = "/redshift/"
tags = [
	"redshift"
]

[[files]]
file = "ristretto/accels.scm"
tags = [
	"ristretto"
]

[[files]]
file = "/sakura/"

[[files]]
file = "/sparta/"

[[files]]
file = "/starship/"
tags = [
	"starship"
]

[[files]]
file = "/termite/"

[[files]]
file = "/tilda/"

[[files]]
file = "/wget/"
tags = [
	"wget"
]

[[files]]
file = "/infokey/"

[[files]]
file = "/X11/"
tags = [
	"X"
]

[[files]]
file = "/xfce4/terminal/"
tags = [
	"xfce4"
]

[[files]]
file = "/yay/"
tags = [
	"yay"
]

[[files]]
file = "/xob/"
tags = [
	"xob"
]

#
# ~/.local/share/applications
#

[[files]]
file = "/obsidian.desktop"
tags = [
	"obsidian"
]

[[files]]
file = "/zettlr.desktop"
tags = [
	"zettlr"
]

#
# ~/scripts
#

# bugged unless we add full directory ignores
# [[files]]
# file = "/scripts/"
