#
# setups
#


#
# ignores
#

[[ignores]]
file = "/bash-it/"

[[ignores]]
file = "/oh-my-zsh/"

#
# ~
#

[[files]]
file = "/.bash_logout"
tags = [
	"bash"
]

[[files]]
file = "/.bash_profile"
tags = [
	"bash"
]

[[files]]
file = "/.bashrc"
tags = [
	"bash"
]

[[files]]
file = "/.cliflix.json"
tags = [
	"cliflix"
]

[[files]]
file = "/.fehbg"
tags = [
	"feh"
]


[[files]]
file = "/.profile"
tags = [
	"shell"
]

[[files]]
file = "/.xinitrc"
tags = [
	"X"
]

[[files]]
file = "/.xprofile"
tags = [
	"X"
]

[[files]]
file = "/.Xresources"
tags = [
	"X"
]

[[files]]
file = "/.zprofile"
tags = [
	"zsh"
]

[[files]]
file = "/.zshrc"
tags = [
	"zsh"
]

#
# ~/config
#

[[files]]
file = "/user-dirs.dirs"

[[files]]
file = "/alacritty/"
tags = [
	"alacritty"
]

[[files]]
file = "/awesome/"
tags = [
	"awesome"
]

[[files]]
file = "/bash/"
tags = [
	"bash"
]

[[files]]
file = "/calcurse/"
tags = [
	"calcurse"
]

[[files]]
file = "/cava/"
tags = [
	"cava"
]

[[files]]
file = "/chezmoi/"
tags = [
	"chezmoi"
]

[[files]]
file = "/cmus/rc"
tags = [
	"cmus"
]

[[files]]
file = "/Code/User/keybindings.json"
tags = [
	"vscode"
]

[[files]]
file = "/Code/User/settings.json"
tags = [
	"vscode"
]

[[files]]
file = "/curl/"
tags =  [
	"curl"
]

[[files]]
file = "/dircolors/"

[[files]]
file = "/fish/"
tags = [
	"fish"
]

[[files]]
file = "/fontconfig/"

[[files]]
file = "/gh/"
tags = [
	"gh"
]

[[files]]
file = "/git/"
tags = [
	"git"
]

[[files]]
file = "/gnupg/gpg-agent.conf"
tags = [
	"gnupg"
]

[[files]]
file = "/hg/"
tags = [
	"mercurial"
]

[[files]]
file = "/i3/"
tags = [
	"i3"
]

[[files]]
file = "/i3status/"
tags = [
	"i3status"
]

[[files]]
file = "/info/"

[[files]]
file = "/ion/"
tags = [
	"ion"
]

[[files]]
file = "/kitty/"

[[files]]
file = "/maven/"

[[files]]
file = "/micro/bindings.json"
tags = [
	"micro"
]

[[files]]
file = "/micro/settings.json"
tags = [
	"micro"
]

[[files]]
file = "/mnemosyne/config.py"
tags = [
	"mnemosyne"
]

[[files]]
file = "/nano/"
tags = [
	"nano"
]

[[files]]
file = "/neofetch/"
tags = [
	"neofetch"
]

[[files]]
file = "/npm/"
tags = [
	"npm"
]

[[files]]
file = "/nu/"
tags = [
	"nu"
]

[[files]]
file = "/nvim/"
tags = [
	"nvim"
]

[[files]]
file = "/picom/"
tags = [
	"picom"
]

[[files]]
file = "/polybar/"
tags = [
	"polybar"
]

[[files]]
file = "/ranger/"
tags = [
	"ranger"
]

[[files]]
file = "/readline/"
tags = [
	"bash", "redline"
]

[[files]]
file = "/redshift/"
tags = [
	"redshift"
]

[[files]]
file = "ristretto/accels.scm"
tags = [
	"ristretto"
]

[[files]]
file = "/sakura/"
tags = [
	"sakura"
]

[[files]]
file = "/sparta/"
tags = [
	"sparta"
]

[[files]]
file = "/starship/"
tags = [
	"starship"
]

[[files]]
file = "/termite/"
tags = [
	"termite"
]

[[files]]
file = "/tilda/"
tags = [
	"tilda"
]

[[files]]
file = "/vim/"
tags = [
	"vim"
]

[[files]]
file = "/wget/"
tags = [
	"wget"
]

[[files]]
file = "/infokey/"
tags = [
	"info"
]

[[files]]
file = "/X11/"
tags = [
	"X"
]

[[files]]
file = "/yay/"
tags = [
	"yay"
]

[[files]]
file = "/xob/"
tags = [
	"xob"
]

#
# ~/.local/share/applications
#

[[files]]
file = "/obsidian.desktop"
tags = [
	"obsidian"
]

[[files]]
file = "/zettlr.desktop"
tags = [
	"zettlr"
]

#
# ~/scripts
#

[[files]]
file = "/scripts/"
