#
# ~
#

[[files]]
file = "/.bash_logout"
tags = [
	"bash"
]

[[files]]
file = "/.bash_profile"
tags = [
	"bash"
]

[[files]]
file = "/.bashrc"
tags = [
	"bash"
]

[[files]]
file = "/.cliflix.json"
tags = [
	"cliflix"
]

[[files]]
file = "/.cshrc"
tags = [
	"cshrc"
]

[[files]]
file = "/.fehbg"
tags = [
	"feh"
]

[[files]]
file = "/.kshrc"
tags = [
	"ksh"
]

[[files]]
file = "/.login"
tags = [
	"cshrc", "tcshrc"
]

[[files]]
file = "/.profile"
tags = [
	"shell"
]

[[files]]
file = "/.rcrc"
tags = [
	"rcm"
]

[[files]]
file = "/.tcshrc"
tags = [
	"tcshrc"
]

[[files]]
file = "/.xinitrc"
tags = [
	"X"
]

[[files]]
file = "/.xprofile"
tags = [
	"X"
]

[[files]]
file = "/.Xresources"
tags = [
	"X"
]

[[files]]
file = "/.zprofile"
tags = [
	"zsh"
]

[[files]]
file = "/.zshrc"
tags = [
	"zsh"
]

#
# ~/.config
#

[[files]]
file = "/user-dirs.dirs"

[[files]]
file = "/alacritty"
type = "folder"

[[files]]
file = "/awesome"
type = "folder"

[[files]]
file = "/bash"
type = "folder"

[[files]]
file = "/calcurse"
type = "folder"

[[files]]
file = "/cava"
type = "folder"

[[files]]
file = "/chezmoi"
type = "folder"

[[files]]
file = "/cmus/rc"
type = "file"

[[files]]
file = "/Code/User/keybindings.json"

[[files]]
file = "/Code/User/settings.json"

[[files]]
file = "/curl"
type = "folder"

[[files]]
file = "/dircolors"
type = "folder"

[[files]]
file = "/fish"
type = "folder"

[[files]]
file = "/fontconfig"
type =  "folder"

[[files]]
file = "/gh"
type = "folder"

[[files]]
file = "/git"
type = "folder"

[[files]]
file = "/gnupg/gpg-agent.conf"

[[files]]
file = "/hg"
type = "folder"

[[files]]
file = "/i3"
type = "folder"
tags = [
	"i3"
]

[[files]]
file = "/i3status"
type = "folder"
tags = [
	"i3status"
]

[[files]]
file = "/info"
type = "folder"

[[files]]
file = "/ion"
type = "folder"
tags = [
	"ion"
]

[[files]]
file = "/kitty"
type = "folder"

[[files]]
file = "/maven"
type = "folder"

[[files]]
file = "/micro/bindings.json"
tags = [
	"micro"
]

[[files]]
file = "/micro/settings.json"
tags = [
	"micro"
]

[[files]]
file = "/mnemosyne/config.py"
tags = [
	"mnemosyne"
]

[[files]]
file = "/nano"
type = "folder"

[[files]]
file = "/neofetch"
type = "folder"

[[files]]
file = "/npm"
type = "folder"

[[files]]
file = "/nu"
type = "folder"

[[files]]
file = "/nvim"
type = "folder"

[[files]]
file = "/picom"
type = "folder"

[[files]]
file = "/polybar"
type = "folder"

[[files]]
file = "/ranger"
type = "folder"
tags = [
	"ranger"
]

[[files]]
file = "/readline"
type = "folder"
tags = [
	"bash", "redline"
]

[[files]]
file = "/redshift"
type = "folder"
tags = [
	"redshift"
]

[[files]]
file = "ristretto/accels.scm"
tags = [
	"ristretto"
]

[[files]]
file = "/sakura"
type = "folder"

[[files]]
file = "/sparta"
type = "folder"

[[files]]
file = "/starship"
type = "folder"
tags = [
	"starship"
]

[[files]]
file = "/termite"
type = "folder"

[[files]]
file = "/tilda"
type = "folder"

[[files]]
file = "/wget"
type = "folder"
tags = [
	"wget"
]

[[files]]
file = "/infokey"

[[files]]
file = "/X11"
type = "folder"
tags = [
	"X"
]

[[files]]
file = "/xfce4/terminal"
type = "folder"
tags = [
	"xfce4"
]

[[files]]
file = "/yay"
type = "folder"
tags = [
	"yay"
]

[[files]]
file = "/xob"
type = "folder"

#
# ~/.local/share/applications
#

[[files]]
file = "/obsidian.desktop"
tags = [
	"obsidian"
]

[[files]]
file = "/zettlr.desktop"
tags = [
	"zettlr"
]

#
# ~/scripts
#

[[files]]
file = "/scripts"
type = "folder"
